import type { ThemeDefinition } from "../types";

export const githubLight: ThemeDefinition = {
  name: "github-light",
  label: "GitHub Light",
  scheme: "light",
  shikiTheme: "github-light",
  tokens: {
    "--color-bg": "#ffffff",
    "--color-bg-subtle": "#f6f8fa",
    "--color-bg-inset": "#eaeef2",
    "--color-bg-overlay": "#ffffff",
    "--color-border": "#d0d7de",
    "--color-border-muted": "#e8ecef",
    "--color-text": "#1f2328",
    "--color-text-secondary": "#57606a",
    "--color-text-muted": "#6e7781",
    "--color-accent": "#0969da",
    "--color-accent-hover": "#0550ae",
    "--color-accent-fg": "#ffffff",
    "--color-accent-subtle": "#dbeafe",
    "--color-sidebar-bg": "#f6f8fa",
    "--color-sidebar-border": "#d0d7de",
    "--color-sidebar-hover": "rgba(0,0,0,0.04)",
    "--color-sidebar-active": "#dbeafe",
    "--color-sidebar-active-text": "#0969da",
    "--color-tab-bg": "#f0f2f4",
    "--color-tab-active": "#ffffff",
    "--color-tab-hover": "#e8ecef",
    "--color-tab-border": "#d0d7de",
    "--color-titlebar-bg": "#f6f8fa",
    "--color-titlebar-text": "#1f2328",
    "--color-titlebar-border": "#d0d7de",
    "--color-status-bg": "#0969da",
    "--color-status-text": "#ffffff",
    "--color-syntax-bg": "#f6f8fa",
    "--color-activity-bg": "#eaeef2",
    "--color-activity-icon": "#57606a",
    "--color-activity-icon-active": "#0969da",
    "--color-scrollbar": "rgba(0,0,0,0.15)",
    "--color-scrollbar-hover": "rgba(0,0,0,0.25)",
    "--color-search-match": "rgba(255,213,0,0.5)",
    "--color-search-match-current": "rgba(255,160,0,0.7)",
    "--radius": "6px",
    "--radius-sm": "4px",
    "--radius-lg": "10px",
    "--shadow-sm": "0 1px 3px rgba(0,0,0,0.08)",
    "--shadow-md": "0 4px 12px rgba(0,0,0,0.12)",
    "--shadow-lg": "0 8px 24px rgba(0,0,0,0.16)",
  },
};
