import type { ThemeDefinition } from "../types";

export const solarizedLight: ThemeDefinition = {
  name: "solarized-light",
  label: "Solarized Light",
  scheme: "light",
  shikiTheme: "solarized-light",
  tokens: {
    "--color-bg": "#fdf6e3",
    "--color-bg-subtle": "#eee8d5",
    "--color-bg-inset": "#e5ddc8",
    "--color-bg-overlay": "#fdf6e3",
    "--color-border": "#c9c3b0",
    "--color-border-muted": "#d8d2bf",
    "--color-text": "#586e75",
    "--color-text-secondary": "#657b83",
    "--color-text-muted": "#93a1a1",
    "--color-accent": "#268bd2",
    "--color-accent-hover": "#1a7ac4",
    "--color-accent-fg": "#fdf6e3",
    "--color-accent-subtle": "#c4dff2",
    "--color-sidebar-bg": "#eee8d5",
    "--color-sidebar-border": "#c9c3b0",
    "--color-sidebar-hover": "rgba(0,0,0,0.04)",
    "--color-sidebar-active": "#c4dff2",
    "--color-sidebar-active-text": "#268bd2",
    "--color-tab-bg": "#e8e2cf",
    "--color-tab-active": "#fdf6e3",
    "--color-tab-hover": "#ddd7c4",
    "--color-tab-border": "#c9c3b0",
    "--color-titlebar-bg": "#eee8d5",
    "--color-titlebar-text": "#586e75",
    "--color-titlebar-border": "#c9c3b0",
    "--color-status-bg": "#268bd2",
    "--color-status-text": "#fdf6e3",
    "--color-syntax-bg": "#eee8d5",
    "--color-activity-bg": "#e5ddc8",
    "--color-activity-icon": "#93a1a1",
    "--color-activity-icon-active": "#268bd2",
    "--color-scrollbar": "rgba(0,0,0,0.15)",
    "--color-scrollbar-hover": "rgba(0,0,0,0.25)",
    "--color-search-match": "rgba(181,137,0,0.3)",
    "--color-search-match-current": "rgba(203,75,22,0.4)",
    "--radius": "6px",
    "--radius-sm": "4px",
    "--radius-lg": "10px",
    "--shadow-sm": "0 1px 3px rgba(0,0,0,0.08)",
    "--shadow-md": "0 4px 12px rgba(0,0,0,0.12)",
    "--shadow-lg": "0 8px 24px rgba(0,0,0,0.16)",
  },
};
